# Generated by Django 3.2.16 on 2023-05-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230513_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коммент', 'verbose_name_plural': 'Комменты'},
        ),
    ]
